FunacionCrude/Controllers/PadrinosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FunacionCrude.Models.DAL;
using FunacionCrude.Models.Entities;
using FunacionCrude.ViewModels;
using FunacionCrude.Models.Business;
using FunacionCrude.Models.Abstract;

namespace FunacionCrude.Controllers
{
    public class PadrinosController : Controller
    {
        
        private readonly IPadrinoBusiness _padrinoBusiness;

         public PadrinosController(IPadrinoBusiness padrinoBusiness)
        {
            _padrinoBusiness = padrinoBusiness;
        }

        // GET: Padrinos


        public async Task<IActionResult> Index()
        {
           return View(await _padrinoBusiness.ObtenerListaPadrinos());
        }
       
        // GET: Padrinos/Details/5
         public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var padrino = await _padrinoBusiness.ObtenerPadrinoPorId(id.Value);
            if (padrino == null)
            {
                return NotFound();
            }

            return View(padrino);
        }

        // GET: Padrinos/Create
        public IActionResult Create()
        {
            /*ViewData["listaUsuarios"] = new SelectList(_padrinoBusiness.ObtenerListaUsuarios(), "UsuarioId", "Rol");*/
            return View();
        }


        // POST: Padrinos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PadrinoId,Nombre,Correo,Edad,Profesion,Descripcion")] Padrino padrino)
        {
            if (ModelState.IsValid)
            {
                var padrinoTemp =  await _padrinoBusiness.ObtenerPadrinoPorCorreo(padrino.Correo);

                if (padrinoTemp == null)
                {
                    await _padrinoBusiness.GuardarPadrino(padrino);
                    return RedirectToAction(nameof(Index));
                }
            }


           
            ViewData["errorDoc"] = "Se encuentra registrado un empleado con este documento";

            

            return View(padrino);
            
        }
        

        // GET: Padrinos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var padrino = await _padrinoBusiness.ObtenerPadrinoPorId(id.Value);
            if (padrino == null)
            {
                return NotFound();
            }
            return View(padrino);
        }
      

        // POST: Padrinos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PadrinoId,Nombre,Correo,Edad,Profesion,Descripcion")] Padrino padrino)
        {
            if (id != padrino.PadrinoId)
            {
                return NotFound();
            }
            var padrinoTemp = await _padrinoBusiness.ObtenerPadrinoPorCorreo(padrino.Correo);
            if (padrinoTemp == null || (padrinoTemp.PadrinoId==padrino.PadrinoId))
            {
                if (ModelState.IsValid)
                {
                    await _padrinoBusiness.EditarPadrino(padrino);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(padrino);
        }
        // GET: Padrinos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var padrino = await _padrinoBusiness.ObtenerPadrinoPorId(id.Value);
            await _padrinoBusiness.EliminarPadrino(padrino);
            if (padrino == null)
            {
                return NotFound();
            }
                     

            return RedirectToAction(nameof(Index));

            
        }

       
    }
}

FunacionCrude/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FunacionCrude</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FunacionCrude</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Padrinos" asp-action="Index">Padrinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Privacy" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FunacionCrude - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>